spring:
  application:
    name: store-media-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.mars-ssn.ru/realms/school-social-network

  datasource:
    url: jdbc:postgresql://localhost:5433/store_media_db
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    producer:
      retries: 3
      acks: all
      properties:
        linger.ms: 10
      #key-serializer: org.apache.kafka.common.serialization.LongSerializer
      batch-size: 16384
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
    properties:
      security.protocol: PLAINTEXT

server:
  port: 8083
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Mars123asd!
    key-store-type: PKCS12
    key-alias: mars-ssn


cloudflare:
  r2:
    access-key: 917b120f1552720cc976e9d099220a44
    secret-key: 4b3bebd1399b275fb21955340d19ce2d3fcbe5e43bf6d54cea9ababd7910c7a7
    region: auto
    endpoint: https://b7ef08b6a91cbef5c9b9a2c4b3ba0d33.r2.cloudflarestorage.com
    bucket: ssn-messenger-media
