version: '3.9'
services:
  redis-7000:
    image: redis:7.2
    container_name: redis-7000
    ports:
      - "7000:7000"
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  redis-7001:
    image: redis:7.2
    container_name: redis-7001
    ports:
      - "7001:7001"
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  redis-7002:
    image: redis:7.2
    container_name: redis-7002
    ports:
      - "7002:7002"
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  redis-7003:
    image: redis:7.2
    container_name: redis-7003
    ports:
      - "7003:7003"
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  redis-7004:
    image: redis:7.2
    container_name: redis-7004
    ports:
      - "7004:7004"
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

  redis-7005:
    image: redis:7.2
    container_name: redis-7005
    ports:
      - "7005:7005"
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
