version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - local

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: start-dev --https-port=8443 --https-key-store-file=/opt/keycloak/conf/keycloak.p12 --https-key-store-password=changeit
    restart: always
    links:
      - postgres
    ports:
      - "9082:8080"
      - "8443:8443"  # Добавляем порт для HTTPS
    volumes:
      - ./backups/keycloak:/opt/keycloak  # Пробрасываем сохранённые файлы обратно
      - ./backups/certs:/opt/keycloak/conf  # Пробрасываем SSL-сертификаты
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@1234
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/keycloak.p12  # Указываем путь к SSL
      KC_HTTPS_CERTIFICATE_PASSWORD: changeit
    networks:
      - local

networks:
  local:
