spring:
  application:
    name: store-media-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.mars-ssn.ru/realms/school-social-network


  r2dbc:
    url: r2dbc:postgresql://localhost:5433/store_media_db
    username: admin
    password: 123


  flyway:
    url: jdbc:postgresql://localhost:5433/store_media_db
    user: admin
    password: 123
    locations: classpath:db/migration
    enabled: false
    validate-on-migrate: true
    baseline-on-migrate: true


  kafka:
    bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
    producer:
      retries: 3
      acks: all
      properties:
        linger.ms: 10
      #key-serializer: org.apache.kafka.common.serialization.LongSerializer
      batch-size: 16384
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
    properties:
      security.protocol: PLAINTEXT

server:
  port: 8083
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: Mars123asd!
    key-store-type: PKCS12
    key-alias: mars-ssn

s3:
  region: eu-north-1
#  endpoint: https://b7ef08b6a91cbef5c9b9a2c4b3ba0d33.r2.cloudflarestorage.com
  bucket: school-social-network

logging:
  level:
    root: INFO
    software.amazon.awssdk: DEBUG
    software.amazon.awssdk.request: TRACE  # лог HTTP-запросов и ответов
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.http: DEBUG
    org.flywaydb.core: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc: DEBUG
